name: Daily Crypto Bot Alert

on:
  schedule:
    - cron: '30 3 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install yfinance pandas numpy requests upstox-python-sdk

      - name: Run Alert Bot
        env:
          BOT_TOKEN: ${{ secrets.8622834558:AAH3FP_N54Z9_2QX2U5gALm5KdVVwI3ZGc8 }}
          CHAT_ID: ${{ secrets.6860978416 }}
          UPSTOX_ACCESS_TOKEN: ${{ secrets.UPSTOX_ACCESS_TOKEN }}
        
        run: |
          python main.py
          
